plugins {
    id 'java'
    id 'application'
}

group = 'com.samtindal.usptoconnector'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // Use Java 21
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // SLF4J for logging
    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'ch.qos.logback:logback-classic:1.4.11' // Logback as the SLF4J backend

    // AWS SDK for Lambda and CloudWatch
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.3'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.0'
    implementation 'com.amazonaws:aws-lambda-java-log4j2:1.5.1'

    // HTTP Client for USPTO OpenSearch API communication
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.2.1'

    // JUnit for testing
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

application {
    // Define the main class
    mainClass = 'com.samtindal.usptoconnector.LambdaHandler'
}

tasks.test {
    useJUnitPlatform()
}
